version: '3'

volumes:
  postgres_imageRepository:
    driver: local

services:

  imageRepo:
    build: ./
    image: srpoe/image-repo
    restart: always
    environment:
      imageRepo.db.host: "postgres-imageRepository-db:5432"
      imageRepo.ftp.host: "sftp-imageRepository"
      imageRepo.ftp.port: "22"
      imageRepo.ftp.username: "img"
      imageRepo.ftp.password: "img123"
      imageRepo.ftp.dir: "/imageRepository"
    ports:
      - 8080:8080
    depends_on:
      - postgres-imageRepository-db
      - sftp-imageRepository

  postgres-imageRepository-db:
    image: postgres:13.1-alpine
    volumes:
      - /postgres_imageRepository:/var/lib/postgres
    restart: always
    environment:
      POSTGRES_DB: imageRepository
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      PG_DATA: /var/lib/postgres
    ports:
      - 5431:5432

  adminer:
    image: adminer:4.7.8-standalone
    restart: always
    ports:
      - 8090:8080

  sftp-imageRepository:
    image: atmoz/sftp:alpine
    restart: always
    ports:
      - "22021:22"
    command: img:img123:::imageRepository