server:
  servlet:
    context-path: /api


imageRepo.db.host: localhost:5431
imageRepo.ftp.host: localhost
imageRepo.ftp.port: 22021
imageRepo.ftp.username: img
imageRepo.ftp.password: img123
imageRepo.ftp.dir: "/imageRepository"

spring:
  datasource:
    url: jdbc:postgresql://${imageRepo.db.host}/imageRepository
    username: root
    password: root

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      max-file-size: 5GB
      max-request-size: 5GB

sftp:
  host: ${imageRepo.ftp.host}
  port: ${imageRepo.ftp.port}
  username: ${imageRepo.ftp.username}
  password: ${imageRepo.ftp.password}
  directory:
    remote: ${imageRepo.ftp.dir}
  active: true

security:
  symetricKey: "bla"
